default_challenge: captcha/Math
description: 'Этот вопрос задается для того, чтобы выяснить, являетесь ли Вы человеком или представляете из себя автоматическую спам-рассылку.'
administration_mode: false
allow_on_admin_pages: false
add_captcha_description: true
default_validation: 1
persistence: 1
enable_stats: true
log_wrong_responses: true
_core:
  default_config_hash: pfrv6lPS72f5WG1UB4wHkgQV2invlHwVpaCy_mY-ClQ
langcode: ru
