smtp_on: true
smtp_host: 193.242.149.41
smtp_hostbackup: ''
smtp_port: '25'
smtp_protocol: standard
smtp_username: robot@centerstart.ru
smtp_password: Edf%7854UnR
smtp_from: robot@centerstart.ru
smtp_fromname: 'Администратор сайта'
smtp_client_hostname: centerstart.ru
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
langcode: ru
