page_title: 'Карта сайта'
message:
  value: ''
  format: plain_text
plugins:
  'book:37':
    enabled: false
    weight: -50
    settings:
      title: 'Сведения об образовательной организации'
      show_expanded: true
  'book:52':
    enabled: false
    weight: -49
    settings:
      title: 'Аттестация педагогических работников'
      show_expanded: true
  'book:56':
    enabled: false
    weight: -48
    settings:
      title: 'Информационная безопасность'
      show_expanded: true
  frontpage:
    enabled: false
    weight: -47
    settings:
      title: 'Front page'
      rss: /rss.xml
  'menu:account':
    enabled: false
    weight: -46
    settings:
      title: 'User account menu'
      show_disabled: false
  'menu:admin':
    enabled: false
    weight: -45
    settings:
      title: Администрирование
      show_disabled: false
  'menu:devel':
    enabled: false
    weight: -44
    settings:
      title: Development
      show_disabled: false
  'menu:footer':
    enabled: false
    weight: -43
    settings:
      title: Контакты
      show_disabled: false
  'menu:glavnoe-menyu':
    enabled: true
    weight: -42
    settings:
      title: 'Главное меню'
      show_disabled: false
  'menu:menu-third':
    enabled: true
    weight: -41
    settings:
      title: ''
      show_disabled: false
  'menu:main':
    enabled: true
    weight: -40
    settings:
      title: 'Меню сайта'
      show_disabled: false
  'menu:tools':
    enabled: false
    weight: -39
    settings:
      title: Инструменты
      show_disabled: false
  'vocabulary:marker':
    enabled: false
    weight: -38
    settings:
      title: marker
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:tags':
    enabled: false
    weight: -37
    settings:
      title: Теги
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
include_css: false
_core:
  default_config_hash: xu0yG13sSQJcXrOJJqsn44W_hUWAIFHVlphrzxT2ycU
langcode: ru
