features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: sites/default/themes/custom/start_theme/logo.png
favicon:
  use_default: 0
  path: 'public://start.png'
  mimetype: image/png
